# Generated by Django 3.1.6 on 2021-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='api.Permiso'),
        ),
    ]
