# Generated by Django 3.1.6 on 2021-03-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
